//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaritasManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaritasManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addDB_32 {
            get {
                object obj = ResourceManager.GetObject("addDB_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addDB_64 {
            get {
                object obj = ResourceManager.GetObject("addDB_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addusr {
            get {
                object obj = ResourceManager.GetObject("addusr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addusr_color {
            get {
                object obj = ResourceManager.GetObject("addusr_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backupDB_64 {
            get {
                object obj = ResourceManager.GetObject("backupDB_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap browse_folder {
            get {
                object obj = ResourceManager.GetObject("browse_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caritas {
            get {
                object obj = ResourceManager.GetObject("caritas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caritas2 {
            get {
                object obj = ResourceManager.GetObject("caritas2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccby40 {
            get {
                object obj = ResourceManager.GetObject("ccby40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccbynd30 {
            get {
                object obj = ResourceManager.GetObject("ccbynd30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_32 {
            get {
                object obj = ResourceManager.GetObject("chart_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_64 {
            get {
                object obj = ResourceManager.GetObject("chart_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark_icon {
            get {
                object obj = ResourceManager.GetObject("checkmark_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark_icon_2 {
            get {
                object obj = ResourceManager.GetObject("checkmark_icon_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cities&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Aba&lt;/name&gt;
        ///&lt;zip&gt;8127&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abádszalók&lt;/name&gt;
        ///&lt;zip&gt;5241&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaliget&lt;/name&gt;
        ///&lt;zip&gt;7678&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abasár&lt;/name&gt;
        ///&lt;zip&gt;3261&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaújalpár&lt;/name&gt;
        ///&lt;zip&gt;3882&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaújkér&lt;/name&gt;
        ///&lt;zip&gt;3882&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaújlak&lt;/name&gt;
        ///&lt;zip&gt;3815&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaújszántó&lt;/name&gt;
        ///&lt;zip&gt;3881&lt;/zip&gt;
        ///&lt;/city&gt;
        ///&lt;city&gt;
        ///&lt;name&gt;Abaújszolnok&lt;/name&gt;
        ///&lt;zip&gt;3809&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	&lt;cities&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Aba&lt;/name&gt;
        ///			&lt;zip&gt;8127&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abádszalók&lt;/name&gt;
        ///			&lt;zip&gt;5241&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abaliget&lt;/name&gt;
        ///			&lt;zip&gt;7678&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abasár&lt;/name&gt;
        ///			&lt;zip&gt;3261&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abaújalpár&lt;/name&gt;
        ///			&lt;zip&gt;3882&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abaújkér&lt;/name&gt;
        ///			&lt;zip&gt;3882&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abaújlak&lt;/name&gt;
        ///			&lt;zip&gt;3815&lt;/zip&gt;
        ///		&lt;/city&gt;
        ///		&lt;city&gt;
        ///			&lt;name&gt;Abaújszántó&lt;/nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cityList {
            get {
                return ResourceManager.GetString("cityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clothes_0 {
            get {
                object obj = ResourceManager.GetObject("clothes_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clothes_1 {
            get {
                object obj = ResourceManager.GetObject("clothes_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csv_32 {
            get {
                object obj = ResourceManager.GetObject("csv_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csv_64 {
            get {
                object obj = ResourceManager.GetObject("csv_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dir_32 {
            get {
                object obj = ResourceManager.GetObject("dir_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dir_64 {
            get {
                object obj = ResourceManager.GetObject("dir_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_color {
            get {
                object obj = ResourceManager.GetObject("edit_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_icon {
            get {
                object obj = ResourceManager.GetObject("edit_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_32 {
            get {
                object obj = ResourceManager.GetObject("expand_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_64 {
            get {
                object obj = ResourceManager.GetObject("expand_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extreme_aid_0 {
            get {
                object obj = ResourceManager.GetObject("extreme_aid_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap extreme_aid_1 {
            get {
                object obj = ResourceManager.GetObject("extreme_aid_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap female_32 {
            get {
                object obj = ResourceManager.GetObject("female_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food_0 {
            get {
                object obj = ResourceManager.GetObject("food_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap food_1 {
            get {
                object obj = ResourceManager.GetObject("food_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap furniture_0 {
            get {
                object obj = ResourceManager.GetObject("furniture_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap furniture_1 {
            get {
                object obj = ResourceManager.GetObject("furniture_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap game_icons {
            get {
                object obj = ResourceManager.GetObject("game_icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_0 {
            get {
                object obj = ResourceManager.GetObject("home_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_1 {
            get {
                object obj = ResourceManager.GetObject("home_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8 {
            get {
                object obj = ResourceManager.GetObject("icons8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_32 {
            get {
                object obj = ResourceManager.GetObject("info_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_64 {
            get {
                object obj = ResourceManager.GetObject("info_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap male_32 {
            get {
                object obj = ResourceManager.GetObject("male_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meal_0 {
            get {
                object obj = ResourceManager.GetObject("meal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap meal_1 {
            get {
                object obj = ResourceManager.GetObject("meal_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_0 {
            get {
                object obj = ResourceManager.GetObject("medicine_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medicine_1 {
            get {
                object obj = ResourceManager.GetObject("medicine_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus_icon {
            get {
                object obj = ResourceManager.GetObject("minus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paper_32 {
            get {
                object obj = ResourceManager.GetObject("paper_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pawprint_32 {
            get {
                object obj = ResourceManager.GetObject("pawprint_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_icon {
            get {
                object obj = ResourceManager.GetObject("plus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power {
            get {
                object obj = ResourceManager.GetObject("power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power_color {
            get {
                object obj = ResourceManager.GetObject("power_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_32 {
            get {
                object obj = ResourceManager.GetObject("question_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_64 {
            get {
                object obj = ResourceManager.GetObject("question_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_color {
            get {
                object obj = ResourceManager.GetObject("save_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_color {
            get {
                object obj = ResourceManager.GetObject("settings_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skype_48 {
            get {
                object obj = ResourceManager.GetObject("skype_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skype_64 {
            get {
                object obj = ResourceManager.GetObject("skype_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics {
            get {
                object obj = ResourceManager.GetObject("statistics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap statistics_color {
            get {
                object obj = ResourceManager.GetObject("statistics_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aba
        ///Abádszalók
        ///Abaliget
        ///Abasár
        ///Abaújalpár
        ///Abaújkér
        ///Abaújlak
        ///Abaújszántó
        ///Abaújszolnok
        ///Abaújvár
        ///Abda
        ///Abod
        ///Abony
        ///Ábrahámhegy
        ///Ács
        ///Acsa
        ///Acsád
        ///Acsalag
        ///Ácsteszér
        ///Adács
        ///Ádánd
        ///Adásztevel
        ///Adony
        ///Adorjánháza
        ///Adorjás
        ///Ág
        ///Ágasegyháza
        ///Ágfalva
        ///Aggtelek
        ///Agyagosszergény
        ///Ajak
        ///Ajka
        ///Aka
        ///Akasztó
        ///Alacska
        ///Alap
        ///Alattyán
        ///Albertirsa
        ///Alcsútdoboz
        ///Aldebrő
        ///Algyő
        ///Alibánfa
        ///Almamellék
        ///Almásfüzitő
        ///Almásháza
        ///Almáskamarás
        ///Almáskeresztúr
        ///Álmosd
        ///Alsóberecki
        ///Alsóbogát
        ///Alsódobsza
        ///Alsógagy
        ///Alsómocs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string telepulesek {
            get {
                return ResourceManager.GetString("telepulesek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utility_0 {
            get {
                object obj = ResourceManager.GetObject("utility_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utility_1 {
            get {
                object obj = ResourceManager.GetObject("utility_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
